version: '{_version}.{build}'
branches:
  only:
  - master
configuration: Release
platform: Any CPU
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{_version}-{build}'
environment:
  _version: 4.1.0
  matrix:
  - {}
nuget:
  account_feed: true
  project_feed: true
build:
  project: LiquidState\LiquidState.csproj
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: SRVDkFc46GEnfXBrnFu7kFml7ozzCAH8thZ5s4gvneVLKo+5QfINtxAB+xSCCQQi